user:
  security:
    unprotectedURIs: /,/index,/searched,/buscar,/favicon.ico,/webfonts/**/*,/css/**/*,/js/**/*,/img/**/*,/register,/auth/registration,/auth/registrationConfirm,/forgot-password,/sendRegistrationToken,/resetPassword,/changePassword,/savePassword,/oauth/**,/h2-console/**
    disableCSRFdURIs: /h2-console/**

spring:
  datasource:
    url: 'jdbc:h2:mem:BDD_AKDMVM;INIT=CREATE SCHEMA IF NOT EXISTS BDD_AKDMVM;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE'
    username: 'sa'
    password:

  jpa:
    generate-ddl: true #change to false in production mode
    hibernate:
      ddl-auto: create-drop #change to validate in production mode
    show-sql: false
    database-platform: org.hibernate.dialect.H2Dialect
    defer-datasource-initialization: true

  thymeleaf:
    cache: false
  sql:
    init:
      platform: h2