insert into BDD_AKDMVM.TB00_USER(first_name,last_name,email,password,enabled,locked) VALUES ('Diego','B H','user@gmail.com','$2a$10$.dNJIVmCUUqNBi8dTB4Tf.3teRGuZDpwGM2wcCeVwC9AC3SkNmKdu',true,false);
insert into BDD_AKDMVM.TB00_USER(first_name,last_name,email,password,enabled,locked) VALUES ('Diego','B H','admin@gmail.com','$2a$10$.dNJIVmCUUqNBi8dTB4Tf.3teRGuZDpwGM2wcCeVwC9AC3SkNmKdu',true,false);

insert into BDD_AKDMVM.TB00_ROLE(NAME) VALUES ('ROLE_USER');
insert into BDD_AKDMVM.TB00_ROLE(NAME) VALUES ('ROLE_ADMIN');
insert into BDD_AKDMVM.TB00_ROLE(NAME) VALUES ('ROLE_EDITOR');

insert into BDD_AKDMVM.TB00_PRIVILEGE(NAME) VALUES ('READ_PRIVILEGE');
insert into BDD_AKDMVM.TB00_PRIVILEGE(NAME) VALUES ('WRITE_PRIVILEGE');
insert into BDD_AKDMVM.TB00_PRIVILEGE(NAME) VALUES ('BLOG_PRIVILEGE');

INSERT INTO BDD_AKDMVM.TB00_ROLE_PRIVILEGE VALUES (1,1); -- USER

INSERT INTO BDD_AKDMVM.TB00_ROLE_PRIVILEGE VALUES (2,1); -- ADMIN
INSERT INTO BDD_AKDMVM.TB00_ROLE_PRIVILEGE VALUES (2,2);
INSERT INTO BDD_AKDMVM.TB00_ROLE_PRIVILEGE VALUES (2,3);

INSERT INTO BDD_AKDMVM.TB00_ROLE_PRIVILEGE VALUES (3,1); -- EDITOR
INSERT INTO BDD_AKDMVM.TB00_ROLE_PRIVILEGE VALUES (3,3);

INSERT INTO BDD_AKDMVM.TB00_USER_ROLE VALUES (1,1);
INSERT INTO BDD_AKDMVM.TB00_USER_ROLE VALUES (2,2);